/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as DairyRouteImport } from './routes/dairy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MacroRouteImport } from './routes/macro'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as ReportDateRouteImport } from './routes/report.$date'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DairyRoute = DairyRouteImport.update({
  id: '/dairy',
  path: '/dairy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MacroRoute = MacroRouteImport.update({
  id: '/macro',
  path: '/macro',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportDateRoute = ReportDateRouteImport.update({
  id: '/report/$date',
  path: '/report/$date',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/calendar': typeof CalendarRoute
  '/dairy': typeof DairyRoute
  '/login': typeof LoginRoute
  '/macro': typeof MacroRoute
  '/markets': typeof MarketsRoute
  '/sources': typeof SourcesRoute
  '/watchlist': typeof WatchlistRoute
  '/report/$date': typeof ReportDateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/calendar': typeof CalendarRoute
  '/dairy': typeof DairyRoute
  '/login': typeof LoginRoute
  '/macro': typeof MacroRoute
  '/markets': typeof MarketsRoute
  '/sources': typeof SourcesRoute
  '/watchlist': typeof WatchlistRoute
  '/report/$date': typeof ReportDateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/calendar': typeof CalendarRoute
  '/dairy': typeof DairyRoute
  '/login': typeof LoginRoute
  '/macro': typeof MacroRoute
  '/markets': typeof MarketsRoute
  '/sources': typeof SourcesRoute
  '/watchlist': typeof WatchlistRoute
  '/report/$date': typeof ReportDateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/calendar'
    | '/dairy'
    | '/login'
    | '/macro'
    | '/markets'
    | '/sources'
    | '/watchlist'
    | '/report/$date'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/calendar'
    | '/dairy'
    | '/login'
    | '/macro'
    | '/markets'
    | '/sources'
    | '/watchlist'
    | '/report/$date'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/calendar'
    | '/dairy'
    | '/login'
    | '/macro'
    | '/markets'
    | '/sources'
    | '/watchlist'
    | '/report/$date'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  CalendarRoute: typeof CalendarRoute
  DairyRoute: typeof DairyRoute
  LoginRoute: typeof LoginRoute
  MacroRoute: typeof MacroRoute
  MarketsRoute: typeof MarketsRoute
  SourcesRoute: typeof SourcesRoute
  WatchlistRoute: typeof WatchlistRoute
  ReportDateRoute: typeof ReportDateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dairy': {
      id: '/dairy'
      path: '/dairy'
      fullPath: '/dairy'
      preLoaderRoute: typeof DairyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/macro': {
      id: '/macro'
      path: '/macro'
      fullPath: '/macro'
      preLoaderRoute: typeof MacroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$date': {
      id: '/report/$date'
      path: '/report/$date'
      fullPath: '/report/$date'
      preLoaderRoute: typeof ReportDateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  CalendarRoute: CalendarRoute,
  DairyRoute: DairyRoute,
  LoginRoute: LoginRoute,
  MacroRoute: MacroRoute,
  MarketsRoute: MarketsRoute,
  SourcesRoute: SourcesRoute,
  WatchlistRoute: WatchlistRoute,
  ReportDateRoute: ReportDateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
